/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modelo.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lojarmi.LojaClient;

/**
 *
 * @author Eduardo M
 */
public class pProduto extends javax.swing.JFrame {

    /**
     * Creates new form pProduto
     */
    private List<Produto> lP = new ArrayList<>();
    private LojaClient Client = new LojaClient();
    private String s;
    public pProduto() {
        initComponents();
        Btn_OrdemActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text_Pesquisa = new javax.swing.JTextField();
        Btn_pesq = new javax.swing.JButton();
        Btn_limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Btn_novo = new javax.swing.JButton();
        Cb_tipo = new javax.swing.JComboBox();
        Btn_Ordem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pesquisa:");

        Text_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_PesquisaActionPerformed(evt);
            }
        });

        Btn_pesq.setText("Pesquisar");
        Btn_pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_pesqActionPerformed(evt);
            }
        });

        Btn_limpar.setText("Limpar");
        Btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limparActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Tipo", "Quantidade", "Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        Btn_novo.setText("Fazer Venda");
        Btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_novoActionPerformed(evt);
            }
        });

        Cb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "TV", "Fogão", "Celular", "Fone", "Lavadora" }));

        Btn_Ordem.setText("Ordem Crescente");
        Btn_Ordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OrdemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(Btn_novo)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Ordem)
                        .addGap(48, 48, 48))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Text_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(102, 102, 102)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Btn_pesq)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(Btn_limpar)))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Btn_Ordem)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_novo)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Btn_pesq)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_limpar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Text_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(417, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_PesquisaActionPerformed

    private void Btn_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_pesqActionPerformed
        // TODO add your handling code here:
        AtualizarGrid(s);
    }//GEN-LAST:event_Btn_pesqActionPerformed

    private void Btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limparActionPerformed
        // TODO add your handling code here:
        Text_Pesquisa.setText("");
        Cb_tipo.setSelectedIndex(0);
        AtualizarGrid(s);
    }//GEN-LAST:event_Btn_limparActionPerformed

    private void Btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_novoActionPerformed
        // TODO add your handling code here:
        if (Tabela.getSelectedRow() >= 0) {
            sProduto cad = new sProduto(Client.PesquisaProduto(Integer.parseInt(Tabela.getValueAt(
                    Tabela.getSelectedRow(), 0).toString())), pProduto.this, s);
            cad.setVisible(true);
        }
    }//GEN-LAST:event_Btn_novoActionPerformed

    private void Btn_OrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OrdemActionPerformed
        // TODO add your handling code here:
        AtualizarGrid(Btn_Ordem.getText());
        s = Btn_Ordem.getText();
        if (Btn_Ordem.getText() == "Ordem Crescente") {
            Btn_Ordem.setText("Ordem decrescente");
            
        } else {
            Btn_Ordem.setText("Ordem Crescente");
        }
    }//GEN-LAST:event_Btn_OrdemActionPerformed
    private String Tipo(int s) {
        if (s == 0) {
            return "TV";
        } else if (s == 1) {
            return "Fogão";
        } else if (s == 2) {
            return "Celular";
        } else if (s == 3) {
            return "Fone";
        } else {
            return "Lavadora";
        }
    }

    public void AtualizarGrid(String tipo) {
        lP = Client.CarregarProduto();
        DefaultTableModel grid = (DefaultTableModel) Tabela.getModel();
        int aux = grid.getRowCount();
        for (int i = 0; i < aux; i++) {
            grid.removeRow(0);
        }
        if (tipo == "Ordem Crescente") {
            if (Cb_tipo.getSelectedIndex() == 0) {
                for (int i = 0; i < lP.size(); i++) {

                    if (lP.get(i).getNome().toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())
                            || Tipo(lP.get(i).getTipo()).toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())
                            || String.valueOf(lP.get(i).getId()).toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())) {
                        grid.addRow(new String[]{
                            String.valueOf(lP.get(i).getId()),
                            lP.get(i).getNome(),
                            Tipo(lP.get(i).getTipo()),
                            String.valueOf(lP.get(i).getQuantidade()),
                            String.valueOf(lP.get(i).getVenda())

                        });
                    }

                }
            } else {
                for (int i = 0; i < lP.size(); i++) {

                    if ((lP.get(i).getNome().toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())
                            || String.valueOf(lP.get(i).getId()).toLowerCase().contains(Text_Pesquisa.getText().toLowerCase()))
                            && lP.get(i).getTipo() == Cb_tipo.getSelectedIndex() - 1) {
                        grid.addRow(new String[]{
                            String.valueOf(lP.get(i).getId()),
                            lP.get(i).getNome(),
                            Tipo(lP.get(i).getTipo()),
                            String.valueOf(lP.get(i).getQuantidade()),
                            String.valueOf(lP.get(i).getVenda())

                        });
                    }

                }
            }
        } else {
            if (Cb_tipo.getSelectedIndex() == 0) {
                for (int i = lP.size() - 1; i >= 0; i--) {

                    if (lP.get(i).getNome().toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())
                            || Tipo(lP.get(i).getTipo()).toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())
                            || String.valueOf(lP.get(i).getId()).toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())) {
                        grid.addRow(new String[]{
                            String.valueOf(lP.get(i).getId()),
                            lP.get(i).getNome(),
                            Tipo(lP.get(i).getTipo()),
                            String.valueOf(lP.get(i).getQuantidade()),
                            String.valueOf(lP.get(i).getVenda())

                        });
                    }

                }
            } else {
                for (int i = lP.size() - 1; i >= 0; i--) {

                    if ((lP.get(i).getNome().toLowerCase().contains(Text_Pesquisa.getText().toLowerCase())
                            || String.valueOf(lP.get(i).getId()).toLowerCase().contains(Text_Pesquisa.getText().toLowerCase()))
                            && lP.get(i).getTipo() == Cb_tipo.getSelectedIndex() - 1) {
                        grid.addRow(new String[]{
                            String.valueOf(lP.get(i).getId()),
                            lP.get(i).getNome(),
                            Tipo(lP.get(i).getTipo()),
                            String.valueOf(lP.get(i).getQuantidade()),
                            String.valueOf(lP.get(i).getVenda())

                        });
                    }

                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ordem;
    private javax.swing.JButton Btn_limpar;
    private javax.swing.JButton Btn_novo;
    private javax.swing.JButton Btn_pesq;
    private javax.swing.JComboBox Cb_tipo;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField Text_Pesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
